
# ^ (If applied, this commit will...) <subject>

# Explain why this change is being made


# Provide links or keys to any relevant tickets, articles or other resources
# Example: Github issue #23


# --- COMMIT END ---
# Remember to
#    Capitalize the subject line
#    Use the imperative mood in the subject line
#    Do not end the subject line with a period
#    Separate subject from body with a blank line
#    Use the body to explain what and why vs. how
#    Can use multiple lines with "-" for bullet points in body
