#!/usr/bin/env bash
set -e

URL="$1"
NAME="${2:-test}.csv"

rm -f "${NAME}"

echo
curl -L "$URL" -o "$NAME"
echo

if file "$NAME" | grep "Zip archive data" > /dev/null; then
    rm -rf csv
    unzip -d "csv" "$NAME"
    echo
    NAME=csv/*
fi;

file $NAME
echo

wc -l $NAME
echo

head -n5 $NAME
echo

tail -n5 $NAME
echo

exit 0
