#!/usr/bin/env bash
set -e

source "${HOME}/.dotfiles-variables"
source "${DOTFILES_ROOT}/util/script-functions"

if [[ -z "${1}" ]]; then
    _d_info "========= DOTFILES ========="
    _d_pull "${DOTFILES_ROOT}"

    if [[ -d "${DOTFILES_ROOT}/gpg" ]]; then
        echo
        _d_info "============ GPG ==========="
        _d_pull "${DOTFILES_ROOT}/gpg"
    fi

    if [[ -d "${DOTFILES_ROOT}/home-manager/home-manager-configurations" ]]; then
        echo
        _d_info "======= HOME MANAGER ======="
        _d_pull "${DOTFILES_ROOT}/home-manager/home-manager-configurations"
    fi
fi

echo
_d_info "========= BOOTSTRAP ========"
_d_indent "${DOTFILES_ROOT}/bootstrap.sh"
