#!/usr/bin/env bash
set -e

get_sudo_prefix() {
    if ! is_root; then
        echo "sudo"
    fi
}

has_unit_enabled() {
    [[ "$(systemctl is-enabled "${1}" 2> /dev/null)" == "enabled" ]]
}

is_root() {
    [[ $(id -u) == 0 ]]
}

log() {
    echo
    echo -e "\033[00;35m===================== \033[00;32m SYSTEM-UPDATE \033[00;35m ======================\033[0m"
    echo -e "\033[00;35m============================================================\033[0m"
    echo -e "[\033[00;34m${1}\033[0m] => ${2}"
    echo
}


update_apt() {
    if ! hash apt > /dev/null 2>&1; then
        return
    fi

    local sudo_prefix="$(get_sudo_prefix)"

    log "apt" "update"
    "${sudo_prefix}" apt update
    log "apt" "upgrade"
    "${sudo_prefix}" apt upgrade -y
    log "apt" "autoclean"
    "${sudo_prefix}" apt autoclean -y
    log "apt" "autoremove"
    "${sudo_prefix}" apt autoremove -y
}

update_dotfiles() {
    if ! hash dotfiles-update > /dev/null 2>&1; then
        return
    fi

    if hash keychain > /dev/null 2>&1; then
        log "dotfiles" "add key"
        keychain "${HOME}/.ssh/modules/vcs/keys/id_rsa.vcs"
    fi

    log "dotfiles" "update"
    dotfiles-update
}

update_nix() {
    if ! hash nix > /dev/null 2>&1; then
        return
    fi

    if [[ -r "${HOME}/.nix-channels" ]] && ! has_unit_enabled "nixos-upgrade.timer" &&
       [[ $(find /nix/var/nix/profiles/per-user -type l -iname "channels-*" -mtime -7 | wc -l) == 0 ]]; then
        log "nix" "update nix-channel"
        nix-channel --update
    fi

    if nix-env --query nix > /dev/null 2>&1; then
        log "nix" "update nix"
        nix-env --upgrade --always nix
    fi

    if [[ -r "${HOME}/.nix-channels" && -r "${HOME}/.config/nixpkgs/home.nix" ]]; then
        log "nix" "home-manager switch"
        home-manager switch -b hm-bak
    fi

    if [[ -r "${HOME}/.nix-channels" ]] && is_root; then
        if hash keychain > /dev/null 2>&1; then
            log "nix" "add key"
            keychain "${HOME}/.ssh/modules/vcs/keys/id_rsa.vcs"
        fi

        log "nix" "update nixos project"
        git -C /etc/nixos pull --prune
        log "nix" "update home-manager project"
        git -C /etc/nixos/home-manager-configurations pull --prune

        for module in /etc/nixos/home-manager-configurations/modules/secrets/ssh/modules/*/; do
            log "nix" "update ssh module $(basename "${module}")"
            git -C "${module}" pull --prune
        done

         log "nix" "builds nixos configuration"
        /etc/nixos/bin/rebuild build
        log "nix" "switches nixos configuration"
        /etc/nixos/bin/rebuild switch
    fi

    if ! has_unit_enabled "nix-gc.timer"; then
        log "nix" "nix-collect-garbage"
        nix-collect-garbage --delete-older-than 14d 2> /dev/null
    fi

    if ! has_unit_enabled "nix-optimise.timer"; then
        log "nix" "nix-store --optimise"
        nix-store --optimise
    fi
}

update_pass() {
    if ! hash pass > /dev/null 2>&1 || is_root; then
        return
    fi

    log "pass" "update repo"
    pass git pull
}

update_snap() {
    if ! hash snap > /dev/null 2>&1 || ! $(snap list > /dev/null 2>&1); then
        return
    fi

    log "snap" "refresh"
    "$(get_sudo_prefix)" snap refresh
}


update_dotfiles
update_pass
update_apt
update_snap
update_nix
