#!/usr/bin/env bash

for i in "${HOME}/projects/pveu/"*/; do
    echo "${i}"
    git -C "${i}" fm
    echo
done

for i in slock; do
    echo "${i}"
    git -C "${HOME}/projects/${i}" fm
    git -C "${HOME}/projects/${i}" st
    echo
done
